### ISSUE TITLE
map example does not compile on Arduino Due

### ISSUE THREAD

**Issue by fkromer** [hideakitai/ArxContainer#1]

**Comment by hideakitai** [comment]
@fkromer Have you solved? If you still have the problem, please feel free to reopen this.

**Comment by fkromer** [comment]
@hideakitai I've tried to declare and assign values to a map object instaance in the global context of `superloop.ino` not inside of `setup()` and not inside of `loop()`. This is of course any other than best practice. In the global context `// initialize with initializer_list
arx::map<String, int> mp {{"one", 1}, {"two", 2}};` does compile. `mp.insert("three", 3); mp["four"] = 4;` does not. If one uses `map`properly everything works fine.
