### ISSUE TITLE
RingBuffer::Iterator class needs reimplementation of some methods from ConstIterator

### ISSUE THREAD

**Issue by solamyl** [hideakitai/ArxContainer#15]
Unfortunately, it seems that my past fixes of RingBuffer's iterators weren't good enough (fixed issue #5 and merged in #6, corrected then in #7).
What is wrong:
 * all methods in Iterator class derived from ConstIterator that are supposed to return `Iterator` object have to be reimplemented. Inherited methods from ConstIterator now return ConstIterator object which is not what we want. Code like this does not work then:
```
iterator it = begin();
*(it + 1) = 111; //inherited operator+() called on iterator returns const_iterator and then cannot be assigned
```
 * costructors that silently constructs Iterator object from ConstIterator should be no necessary - it is like default const/non-const conversion. Of course, conversion is sometimes necessary - so special (explicit) method for this may exist.

 * arithmetics with iterators is broken. These operations should be working fine:
   * iterator_B = iterator_A + int_X;
   * int_X = iterator_B - iterator_A;
   * iterator_A = iterator_B - int_X;

 * `T* ptr` member of ConstIterator should be declared as a `const`. Otherwise initializing from other const objects shows warnings about const/non-const.

**Comment by hideakitai** [comment]
Thank you!
