### ISSUE TITLE
RingBuffer objects have unnecessarily large memory overhead

### ISSUE THREAD

**Issue by solamyl** [hideakitai/ArxContainer#16]
It is not a real bug, but it could be improved ;-)
This code:
```
    arx::array<float, 3> vec3D;
    float float3x[3];

    Serial.print("sizeof(vec3D)=");
    Serial.println(sizeof(vec3D));
    Serial.print("sizeof(float3x)=");
    Serial.println(sizeof(float3x));
```
Shows that simple array of 3 floats has 12 bytes in contrast to arx::array which has 22 bytes with the same payload:
```
sizeof(vec3D)=22
sizeof(float3x)=12
```
Size of arx::array object is:
* head_ iterator (pointer to a data buffer (2),  position of the begining (2))
* tail_ iterator (pointer to a data buffer (2), position of the end (2))
* virtual destructor pointer (2)
* payload (...3x float is 3x4)
But in practise only position of beginning and end and payload are necessary.

I have realized this on my Arduino Nano when working with 3D vectors and ran out of memory quickly :-)
My project uses motion sensor - single reading from accel/gyro/mag, each in 3 dimensions, has 66 bytes, so little fiddling with it and 2 kB of arduino nano mem are gone.

**Comment by hideakitai** [comment]
Thank you!
