### ISSUE TITLE
Problem with Nested Maps

### ISSUE THREAD

**Issue by GRS26** [hideakitai/ArxContainer#18]
Hello,
I was trying to make my code more organized by trying to use nested maps using the ArxContainer Library, like in the following example :
````
arx::map<String, arx::map<String, int>> Package={
                                                {"Names_and_Age", {
                                                                   {"Jon", 9}
````
The problem is I can't access the contents of Names and Age. If I try to use Package["Names_and_Age"]["Jon"], it always returns zero.

```
for (const auto& m : Package) {
   Serial.print("Outer key: ");
   Serial.print(m.first); // Print the outer key

    // Print the inner map's keys and values
   for (const auto& inner_m : m.second) {
        Serial.print("\n");
       Serial.print("Inner key: ");
       Serial.print(inner_m.first); // Print the inner key
        Serial.print(", Value: ");
       Serial.print(inner_m.second); // Print the inner value
       Serial.print("\n");
   }
}
```
I used the above to print the Outer Key, and the Inner Key and it's contents. The output in Serial monitor is this:
`Outer key: Names and Age
Inner key: n, Value: 9`

You can notice the first two letters are missing from Jon. I tried to access with just 'n' but I also the same zero output. I tried with other variations, lowercase, just numbers, but the first two characters are always missing. I also tried creating the nested map in a class within a header and cpp file and separately as part of a library, but all cases gave zero output.

I also tested this in two arduino megas and the result was the same.

**Comment by hideakitai** [comment]
@GRS26 Could you give us the minimal compilable code to reproduce the problem? I couldn't reproduce the issue in my environment.

**Comment by hideakitai** [comment]
If you still need support, please feel free to reopen this issue
