### ISSUE TITLE
map's move operator should construct base, not RingBuffer<T,N>

### ISSUE THREAD

**Issue by NachtRaveVL** [hideakitai/ArxContainer#3]
https://github.com/hideakitai/ArxContainer/blob/5ad694c7a9bc482eccd878efa52108396f134840/ArxContainer.h#L648

This line should be `: base(r) {}` instead, since it inherits down from `RingBuffer<pair<Key, T>, N>`, not `RingBuffer<T, N>`

**Comment by hideakitai** [comment]
Fixd by https://github.com/hideakitai/ArxContainer/pull/6
